"""Add geolocation and admin_code columns

Revision ID: cb94293395b0
Revises: 
Create Date: 2024-08-03 00:56:16.638277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb94293395b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wifi_network')
    with op.batch_alter_table('timestamp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_in_edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('clock_out_edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('break_duration_edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lunch_duration_edited', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('timestamp', schema=None) as batch_op:
        batch_op.drop_column('lunch_duration_edited')
        batch_op.drop_column('break_duration_edited')
        batch_op.drop_column('clock_out_edited')
        batch_op.drop_column('clock_in_edited')

    op.create_table('wifi_network',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
